### ISSUE TITLE
Are you kidding me?

### ISSUE THREAD

**Issue by gogolander** [rwg0/csharpfits#1]
Your code is an unusable piece of crap.
FITS creation is a nightmare made of logical errors, deadlocks and unintelligible exceptions in which the user is constantly chasing its tail trying to obtain all of the pieces he/she needs.
Did you even bother to try it before releasing it?!
My best guess is: no, you just copy-and-pasted the Java package, adding a shit-load of errors in the process. You couldn't even list the correct minimum version of Visual Studio in the README.MD!
Moreover, NONE of the URLs you indicated in this repo or anywhere else is actually working!

**Comment by rwg0** [comment]
In case you didn't read the first two lines of the readme.md, this was forked from code at http://vo.iucaa.ernet.in/~voi/CSharpFITS.html, which has now vanished, with only minor changes for one performance issue.

 If you have complaints about the code then I suggest you go track down the original author.

**Comment by gogolander** [comment]
Either you're forking a broken code or you broke a working code.
Either way, forking is not an excuse: making sure that your code is working is on you.
You really should consider deleting this repository or marking it as not working, as it should be.

**Comment by rwg0** [comment]
Works for my use case. Grow up.
