### ISSUE TITLE
NuGet Package

### ISSUE THREAD

**Issue by elendil-software** [rwg0/csharpfits#3]
Hi,

There is a NuGet package for CSharpFITS : https://www.nuget.org/packages/CSharpFITS/ 
Is that yours, @rwg0 ?
With several places where I managed to download this library that come from different sources, it's difficult to know which one is more up to date.

Regards

Julien

**Comment by rwg0** [comment]
Hi,

the NuGet package is nothing to do with me, sorry.

Robin

**Comment by elendil-software** [comment]
Ok, Thank you.
