### ISSUE TITLE
.NET Standard/.NET Core compatibility

### ISSUE THREAD

**Issue by elendil-software** [rwg0/csharpfits#4]
Hi,

For you information, I forked this project and have done necessary modification to support .NET Standard/.NET Core. "Classic" .NET Frameworks versions are still supported, of course.

I will do a pull request as soon I'm sure all is still working as expected.

Regards

**Comment by rwg0** [comment]
Sounds good - thank you.

**Comment by elendil-software** [comment]
I noticed a problem with the unit tests. Some test cases fail the first time they are executed. Looks like the use FITS files created by other tests cases. So if they are not executed in the correct order they fail.
This problem already exists in the current version.
I will correct that.

**Comment by elendil-software** [comment]
I've done the correction and sent you a pull request
